import Head from "next/head";
import { FC } from "react";
import Footer from "./Footer/Footer";
import Header from "./Header/Header";

interface iMainLayout {
  children: JSX.Element[] | JSX.Element;
  title?: string;
}

const MainLayout: FC<iMainLayout> = ({
  children,
  title = "Жидкости для вейпа",
}) => {
  return (
    <>
      <Head>
        <title>{title} | SmokeTime</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <main>{children}</main>
      <Footer />
    </>
  );
};

export default MainLayout;
